# Generated by Django 4.2.7 on 2026-06-18 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField()),
                ('microsoft_id', models.CharField(max_length=255, unique=True)),
                ('microsoft_email', models.EmailField(max_length=254)),
                ('microsoft_name', models.CharField(max_length=255)),
                ('scopes', models.TextField(blank=True)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Microsoft Token',
                'verbose_name_plural': 'Microsoft Tokens',
            },
        ),
    ]
