# Generated by Django 4.2.7 on 2026-06-21 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rfq', 'RFQ'), ('purchase_order', 'Purchase Order')], default='rfq', max_length=20)),
                ('stage', models.CharField(choices=[('inquiry', 'Inquiry'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('order', 'Order'), ('fulfilled', 'Fulfilled'), ('archived', 'Archived')], default='inquiry', max_length=20)),
                ('email_subject', models.CharField(max_length=500)),
                ('email_sender', models.EmailField(max_length=254)),
                ('email_received_at', models.DateTimeField()),
                ('email_body', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('email', 'Email'), ('manual', 'Manual'), ('test', 'Test')], default='email', help_text='Source of order (email, manual, test)', max_length=20)),
                ('email_message_id', models.CharField(blank=True, db_index=True, help_text='Unique message ID from email provider for deduplication', max_length=500)),
                ('rfq_number', models.CharField(max_length=100, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('supplier_email', models.EmailField(blank=True, help_text='Supplier email address for sending RFQ', max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('items_description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('specifications', models.TextField(blank=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attachment_filename', models.CharField(blank=True, max_length=255)),
                ('attachment_path', models.CharField(blank=True, max_length=500)),
                ('attachment_size', models.IntegerField(blank=True, null=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_errors', models.TextField(blank=True)),
                ('supplier_email_sent', models.BooleanField(default=False)),
                ('supplier_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_email_error', models.TextField(blank=True)),
                ('bc_quote_id', models.CharField(blank=True, help_text='Business Central sales quote ID', max_length=255)),
                ('bc_synced', models.BooleanField(default=False, help_text='Whether order has been synced to BC')),
                ('bc_synced_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Client who sent the RFQ / placed the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='contacts.contact')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier assigned to fulfill this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_orders', to='contacts.contact')),
            ],
            options={
                'db_table': 'rfq_rfq',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_orders_received', models.IntegerField(default=0)),
                ('total_orders_processed', models.IntegerField(default=0)),
                ('total_orders_completed', models.IntegerField(default=0)),
                ('total_orders_rejected', models.IntegerField(default=0)),
                ('avg_processing_time_hours', models.FloatField(blank=True, null=True)),
                ('avg_ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('unique_companies', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Order Analytics',
                'db_table': 'rfq_rfqanalytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_product_id', models.CharField(help_text='Business Central item ID', max_length=255, unique=True)),
                ('number', models.CharField(blank=True, help_text='Item number / SKU', max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('blocked', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'rfq_product',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfq.order')),
            ],
            options={
                'db_table': 'rfq_rfqitem',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rfq.order')),
            ],
            options={
                'db_table': 'rfq_rfqattachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='rfq_rfq_status_208c61_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stage'], name='rfq_rfq_stage_a963ce_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['priority'], name='rfq_rfq_priorit_c61f07_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['type'], name='rfq_rfq_type_9e1e08_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email_received_at'], name='rfq_rfq_email_r_11ace5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['rfq_number'], name='rfq_rfq_rfq_num_b3eeca_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email_sender'], name='rfq_rfq_email_s_4b1d50_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company_name'], name='rfq_rfq_company_13e42e_idx'),
        ),
    ]
