# Generated by Django 4.2.7 on 2026-06-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='probability',
            field=models.IntegerField(default=0, help_text='Win probability percentage (0-100)'),
        ),
    ]
