# Generated by Django 4.2.7 on 2026-06-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_order_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_classification',
            field=models.CharField(choices=[('rfq_po', 'RFQ / PO'), ('quotation', 'Quotation'), ('other', 'Other')], default='other', help_text='AI-classified email type: RFQ/PO, Quotation, or Other', max_length=20),
        ),
    ]
