# Generated by Django 6.0.6 on 2026-06-22 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('rfq', '0003_order_email_classification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Primary supplier assigned to fulfill this order (legacy field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_orders', to='contacts.contact'),
        ),
        migrations.CreateModel(
            name='OrderSupplierAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_assignments', to='rfq.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_assignments', to='contacts.contact')),
            ],
            options={
                'db_table': 'rfq_ordersupplierassignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('order', 'supplier')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='suppliers',
            field=models.ManyToManyField(blank=True, help_text='Multiple suppliers that can fulfill this order', related_name='rfq_suppliers', through='rfq.OrderSupplierAssignment', to='contacts.contact'),
        ),
    ]
