# Generated by Django 6.0.6 on 2026-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0004_alter_order_supplier_ordersupplierassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
