# Generated by Django 6.0.6 on 2026-06-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0005_alter_orderitem_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
