# Generated by Django 6.0.6 on 2026-07-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0006_alter_orderitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase Order number from customer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email_classification',
            field=models.CharField(choices=[('rfq', 'RFQ'), ('po', 'PO'), ('quotation', 'Quotation'), ('other', 'Other')], default='other', help_text='AI-classified email type: RFQ, PO, Quotation, or Other', max_length=20),
        ),
    ]
