# Generated by Django 6.0.6 on 2026-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0007_add_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bc_sales_order_id',
            field=models.CharField(blank=True, help_text='Business Central sales order ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bc_sales_order_number',
            field=models.CharField(blank=True, help_text='Business Central sales order number', max_length=255, null=True),
        ),
    ]
