# Generated by Django 6.0.6 on 2026-07-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0008_add_bc_sales_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quotation_email_sent',
            field=models.BooleanField(default=False, help_text='Whether customer quotation email has been sent for this order'),
        ),
    ]
