# Generated by Django 6.0.6 on 2026-07-06 14:37

from django.db import migrations, models


def remove_duplicate_email_message_ids(apps, schema_editor):
    """Remove duplicate orders with the same email_message_id, keeping the oldest one."""
    Order = apps.get_model('rfq', 'Order')
    
    # Find all email_message_ids that have duplicates
    from django.db.models import Count
    duplicates = Order.objects.exclude(email_message_id='').values('email_message_id').annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    for dup in duplicates:
        msg_id = dup['email_message_id']
        # Get all orders with this message_id, ordered by creation date
        orders = Order.objects.filter(email_message_id=msg_id).order_by('created_at')
        # Keep the first (oldest), delete the rest
        to_delete = orders[1:]
        for order in to_delete:
            print(f"Deleting duplicate order {order.rfq_number} with message_id {msg_id}")
            order.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0009_order_quotation_email_sent'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_email_message_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='email_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique message ID from email provider for deduplication', max_length=500, unique=True),
        ),
    ]
