# Generated by Django 4.2.7 on 2026-07-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0010_add_unique_email_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderattachment',
            name='file_url',
            field=models.CharField(blank=True, help_text='Download link for the attachment', max_length=500),
        ),
    ]
