# Generated by Django 4.2.7 on 2026-07-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0011_orderattachment_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachment_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of download URLs for all attachments (multiple files per email)'),
        ),
    ]
