# Generated by Django 4.2.7 on 2026-07-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0013_backfill_attachment_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderattachment',
            name='source_attachment_id',
            field=models.CharField(blank=True, help_text='Attachment ID from the email provider', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='file_url',
            field=models.CharField(blank=True, help_text='Download link for the attachment as provided by the email source', max_length=500),
        ),
    ]
