# Generated by Django 4.2.7 on 2026-07-31 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0014_orderattachment_source_attachment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='attachment_filename',
        ),
        migrations.RemoveField(
            model_name='order',
            name='attachment_path',
        ),
        migrations.RemoveField(
            model_name='order',
            name='attachment_size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='attachment_urls',
        ),
        migrations.DeleteModel(
            name='OrderAttachment',
        ),
    ]
