# Generated by Django 6.0.5 on 2026-08-01 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0015_remove_order_attachment_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('use', models.CharField(choices=[('classification', 'Classification'), ('image_details', 'Image details'), ('extraction', 'Extraction'), ('general', 'General')], default='general', max_length=30)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('input_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('output_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_records', to='rfq.order')),
            ],
            options={
                'db_table': 'rfq_aiusagerecord',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'model'], name='rfq_aiusage_provide_888926_idx'), models.Index(fields=['use'], name='rfq_aiusage_use_f2197a_idx'), models.Index(fields=['created_at'], name='rfq_aiusage_created_69fbed_idx')],
            },
        ),
    ]
