# Generated by Django 4.2.7 on 2026-08-12 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfq', '0016_aiusagerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message_id', models.CharField(help_text='Microsoft Graph message ID (deduplication key)', max_length=500, unique=True)),
                ('conversation_id', models.CharField(blank=True, db_index=True, help_text='Outlook conversation ID used to group threads', max_length=500)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('body_preview', models.CharField(blank=True, help_text='Plain-text preview of the email body', max_length=500)),
                ('classification', models.CharField(choices=[('rfq', 'RFQ'), ('po', 'PO'), ('quotation', 'Quotation'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, help_text='Order created/updated from this email (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_emails', to='rfq.order')),
                ('user', models.ForeignKey(blank=True, help_text='Operator whose mailbox produced this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rfq_processedemail',
                'ordering': ['-received_at', '-created_at'],
                'indexes': [models.Index(fields=['classification'], name='rfq_process_classif_3312f0_idx'), models.Index(fields=['conversation_id'], name='rfq_process_convers_0124a0_idx')],
            },
        ),
    ]
