# Generated by Django 6.0.5 on 2026-08-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0018_remove_email_sending_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('order', 'Order'), ('fulfilled', 'Fulfilled'), ('synced', 'Synced'), ('archived', 'Archived')], default='inquiry', max_length=20),
        ),
    ]
