# Generated by Django 6.0.5 on 2026-08-30 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0019_alter_order_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('synced', 'Synced'), ('inquiry', 'Inquiry'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('order', 'Order'), ('fulfilled', 'Fulfilled'), ('archived', 'Archived')], default='inquiry', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rfq_emailthread',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('body_preview', models.CharField(blank=True, max_length=500)),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rfq.emailthread')),
            ],
            options={
                'db_table': 'rfq_emailmessage',
                'ordering': ['received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['conversation_id'], name='rfq_emailth_convers_aef970_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['message_id'], name='rfq_emailme_message_6a8a7a_idx'),
        ),
    ]
