# Generated by Django 6.0.5 on 2026-08-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0020_alter_order_stage_emailthread_emailmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('synced', 'Synced'), ('categorized', 'Categorized'), ('inquiry', 'Inquiry'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('order', 'Order'), ('fulfilled', 'Fulfilled'), ('archived', 'Archived')], default='inquiry', max_length=20),
        ),
    ]
