# Generated by Django 6.0.5 on 2026-08-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0022_alter_order_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailthread',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
