# Generated by Django 6.0.5 on 2026-08-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0023_emailthread_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailthread',
            name='stage',
            field=models.CharField(choices=[('synced', 'Synced'), ('ai_analysis', 'AI Analysis'), ('categorized', 'Categorized'), ('inquiry', 'Inquiry'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('order', 'Order'), ('fulfilled', 'Fulfilled'), ('archived', 'Archived')], default='synced', max_length=20),
        ),
    ]
