# Generated by Django 6.0.5 on 2026-08-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0024_emailthread_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
