# Generated by Django 6.0.5 on 2026-08-31 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0025_emailmessage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailthread',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to='rfq.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='email_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='rfq.emailthread'),
        ),
    ]
