# Generated by Django 6.0.5 on 2026-08-31 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('rfq', '0026_emailthread_deal_order_email_thread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAiMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_errors', models.TextField(blank=True)),
                ('classification', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rfq_orderaimetadata',
            },
        ),
        migrations.CreateModel(
            name='OrderBusinessCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(blank=True, max_length=255)),
                ('sales_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rfq_orderbusinesscentral',
            },
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='rfq_rfq_stage_a963ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='rfq_rfq_email_r_11ace5_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='rfq_rfq_email_s_4b1d50_idx',
        ),
        migrations.RemoveField(
            model_name='emailthread',
            name='deal',
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='probability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('email', 'Email'), ('manual', 'Manual'), ('test', 'Test')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Primary supplier assigned to fulfill this order (legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_orders', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='order',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='rfq_suppliers', through='rfq.OrderSupplierAssignment', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='body_preview',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='email_message_id',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_emails', to='rfq.order'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='bc_product_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['stage'], name='rfq_emailth_stage_83d07a_idx'),
        ),
        migrations.AddField(
            model_name='orderaimetadata',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_metadata', to='rfq.order'),
        ),
        migrations.AddField(
            model_name='orderbusinesscentral',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bc_data', to='rfq.order'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='ai_confidence_score',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ai_processed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bc_quote_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bc_sales_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bc_sales_order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bc_synced',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bc_synced_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email_body',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email_classification',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email_message_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email_received_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email_sender',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processing_errors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stage',
        ),
    ]
