# Generated by Django 6.0.5 on 2026-08-31 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0027_orderaimetadata_orderbusinesscentral_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='rfq_rfq_status_208c61_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='rfq_rfq_priorit_c61f07_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
