# Generated by Django 6.0.5 on 2026-08-31 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0028_remove_order_status_priority'),
        ('rfq', '0028_remove_supplier_probability'),
    ]

    operations = [
    ]
