# Generated by Django 4.2.7 on 2026-09-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0029_merge_20260901_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='category',
            field=models.CharField(blank=True, choices=[('rfq', 'RFQ'), ('quotation', 'Quotation'), ('po', 'PO'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailthread',
            name='category',
            field=models.CharField(blank=True, choices=[('rfq', 'RFQ'), ('quotation', 'Quotation'), ('po', 'PO'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='classification',
            field=models.CharField(choices=[('rfq', 'RFQ'), ('quotation', 'Quotation'), ('po', 'PO'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
